spring:
  application:
    name: BuyOrNot

  # DB 연결 - SQL 파일 나오면 datasource 채울 것
  datasource:
    url: jdbc:mysql://localhost:3306/buy_or_not?serverTimezone=Asia/Seoul
    username: root
    password: kwonsj0825
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update        # 개발 중 자동 DDL (운영에서는 none 또는 validate)
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true

  thymeleaf:
    cache: false              # 개발 중 템플릿 캐시 끄기
